version: '3.4'

services:
  database:
    image: postgres
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: 
      - "3000:3000"
    environment:
      RAILS_ENV: development